   /**************************************************************************
   *
   * Copyright 2009 VMware, Inc.
   * All Rights Reserved.
   *
   * Permission is hereby granted, free of charge, to any person obtaining a
   * copy of this software and associated documentation files (the
   * "Software"), to deal in the Software without restriction, including
   * without limitation the rights to use, copy, modify, merge, publish,
   * distribute, sub license, and/or sell copies of the Software, and to
   * permit persons to whom the Software is furnished to do so, subject to
   * the following conditions:
   *
   * The above copyright notice and this permission notice (including the
   * next paragraph) shall be included in all copies or substantial portions
   * of the Software.
   *
   * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
   * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
   * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
   * IN NO EVENT SHALL VMWARE AND/OR ITS SUPPLIERS BE LIABLE FOR
   * ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
   * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
   * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
   *
   **************************************************************************/
      /**
   * @file
   * Symbol lookup.
   *
   * @author Jose Fonseca <jfonseca@vmware.com>
   */
      #include "util/compiler.h"
   #include "util/u_thread.h"
   #include "util/simple_mtx.h"
   #include "util/u_string.h"
      #include "util/u_debug.h"
   #include "u_debug_symbol.h"
   #include "util/hash_table.h"
         #if DETECT_OS_WINDOWS
      #include <windows.h>
   #include <stddef.h>
      #include "dbghelp.h"
         /**
   * SymInitialize() must be called once for each process (in this case, the
   * current process), before any of the other functions can be called.
   */
   static BOOL g_bSymInitialized = false;
         /**
   * Lookup the address of a DbgHelp function.
   */
   static FARPROC WINAPI
   getDbgHelpProcAddress(LPCSTR lpProcName)
   {
               if (!hModule) {
               if (bail) {
            #if DETECT_CC_GCC
         /*
   * DbgHelp does not understand the debug information generated by MinGW toolchain.
   *
   * mgwhelp.dll is a dbghelp.dll look-alike replacement, which is able to
   * understand MinGW symbols, including on 64-bit builds.
   */
   if (!hModule) {
      hModule = LoadLibraryA("mgwhelp.dll");
   if (!hModule) {
      _debug_printf("warning: mgwhelp.dll not found: symbol names will not be resolved\n"
         #endif
            /*
   * Fallback to the real DbgHelp.
   */
   if (!hModule) {
                  if (!hModule) {
      bail = true;
                     }
         /**
   * Generic macro to dispatch a DbgHelp functions.
   */
   #define DBGHELP_DISPATCH(_name, _ret_type, _ret_default, _arg_types, _arg_names) \
      static _ret_type WINAPI \
   j_##_name _arg_types \
   { \
      typedef BOOL (WINAPI *PFN) _arg_types; \
   static PFN pfn = NULL; \
   if (!pfn) { \
      pfn = (PFN) getDbgHelpProcAddress(#_name); \
   if (!pfn) { \
            } \
            DBGHELP_DISPATCH(SymInitialize,
                        DBGHELP_DISPATCH(SymSetOptions,
                        #ifndef _GAMING_XBOX
   DBGHELP_DISPATCH(SymFromAddr,
                     #endif
      DBGHELP_DISPATCH(SymGetLineFromAddr64,
                        DBGHELP_DISPATCH(SymCleanup, BOOL, false, (HANDLE hProcess), (hProcess))
         #undef DBGHELP_DISPATCH
         static inline bool
   debug_symbol_name_dbghelp(const void *addr, char* buf, unsigned size)
   {
   #ifndef _GAMING_XBOX
      DWORD64 dwAddr = (DWORD64)(uintptr_t)addr;
            /* General purpose buffer, to back pSymbol and other temporary stuff.
   * Must not be too memory hungry here to avoid stack overflows.
   */
            PSYMBOL_INFO pSymbol = (PSYMBOL_INFO) buffer;
   DWORD64 dwDisplacement = 0;  /* Displacement of the input address, relative to the start of the symbol */
   DWORD dwLineDisplacement = 0;
            memset(pSymbol, 0, sizeof *pSymbol);
   pSymbol->SizeOfStruct = sizeof *pSymbol;
            if (!g_bSymInitialized) {
      /* Some components (e.g. Java) will init dbghelp before we're loaded, causing the "invade process"
   * option to be invalid when attempting to re-init. But without it, we'd have to manually
   * load symbols for all modules in the stack. For simplicity, we can just uninit and then
   * re-"invade".
   */
   if (debug_get_bool_option("GALLIUM_SYMBOL_FORCE_REINIT", false))
            j_SymSetOptions(/* SYMOPT_UNDNAME | */ SYMOPT_LOAD_LINES);
   if (j_SymInitialize(hProcess, NULL, true)) {
                     /* Lookup symbol name */
   if (!g_bSymInitialized ||
      !j_SymFromAddr(hProcess, dwAddr, &dwDisplacement, pSymbol)) {
   /*
   * We couldn't obtain symbol information.  At least tell which module the address belongs.
                     if (!GetModuleHandleEx(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS,
                              if (GetModuleFileNameA(hModule, buffer, sizeof buffer) == sizeof buffer) {
         }
   snprintf(buf, size, "%p at %s+0x%lx",
                              /*
   * Try to get filename and line number.
   */
   memset(&Line, 0, sizeof Line);
   Line.SizeOfStruct = sizeof Line;
   if (!j_SymGetLineFromAddr64(hProcess, dwAddr, &dwLineDisplacement, &Line)) {
                  if (Line.FileName) {
         } else {
                     #else
         #endif /* _GAMING_XBOX */
   }
      #endif /* DETECT_OS_WINDOWS */
      void
   debug_symbol_name(const void *addr, char* buf, unsigned size)
   {
   #if DETECT_OS_WINDOWS
      if (debug_symbol_name_dbghelp(addr, buf, size)) {
            #endif
         snprintf(buf, size, "%p", addr);
      }
      void
   debug_symbol_print(const void *addr)
   {
      char buf[1024];
   debug_symbol_name(addr, buf, sizeof(buf));
      }
      static struct hash_table* symbols_hash;
   static simple_mtx_t symbols_mutex = SIMPLE_MTX_INITIALIZER;
      const char*
   debug_symbol_name_cached(const void *addr)
   {
      const char* name;
   simple_mtx_lock(&symbols_mutex);
   if(!symbols_hash)
         struct hash_entry *entry = _mesa_hash_table_search(symbols_hash, addr);
   if (!entry) {
      char buf[1024];
   debug_symbol_name(addr, buf, sizeof(buf));
               }
   simple_mtx_unlock(&symbols_mutex);
      }
